[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "flask db upgrade && gunicorn 'sliptrack.app:create_app()' --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level debug"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
